import subprocess
import json
import os
import sys
import argparse
import time

def main():
    """
    Master orchestrator for sequential training of multiple model versions.
    Automatically collects results and generates a comparative summary table.
    """
    parser = argparse.ArgumentParser(description="Master script for sequential TCN training")
    parser.add_argument('--epochs', type=int, default=300, help='Epochs per model')
    parser.add_argument('--batch_size', type=int, default=32, help='Batch size')
    parser.add_argument('--lr', type=float, default=1e-4, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-3, help='Weight decay')
    parser.add_argument('--data_dir', type=str, default='../DATASET', help='Path to dataset')
    args = parser.parse_args()

    versions = ['v1', 'v2', 'v3']
    results = {}

    os.makedirs("results", exist_ok=True)

    # 1. THE MARATHON START
    print("\n" + "="*70)
    print(f"🚀 STARTING THE TRAINING MARATHON (AdamW + Timing)")
    print(f"   Settings: {args.epochs} Epochs | Batch {args.batch_size} | LR {args.lr}")
    print("="*70)

    for v in versions:
        print(f"\n🔄 [MODEL {v.upper()}] Launching...")

        # Constructing the CLI command to trigger train.py
        # Using sys.executable ensures we use the current Python interpreter
        cmd = [
            sys.executable, "-u", "train.py", # -u for unbuffered output (real-time logs)
            "--version", v,
            "--epochs", str(args.epochs),
            "--batch_size", str(args.batch_size),
            "--lr", str(args.lr),
            "--weight_decay", str(args.weight_decay),
            "--data_dir", args.data_dir
        ]

        try:
            # 2. RUNNING THE TRAIN PROCESS
            # stdout/stderr are piped back to the master terminal
            subprocess.run(cmd, stdout=sys.stdout, stderr=sys.stderr, check=True)
        except (subprocess.CalledProcessError, KeyboardInterrupt):
            print(f"\n🛑 Stopped during {v.upper()}")
            break

        # 3. DATA COLLECTION
        # After each run, we look for the JSON results generated by train.py
        res_file = os.path.join("results", f"results_{v}.json")
        if os.path.exists(res_file):
            with open(res_file, "r") as f:
                results[v] = json.load(f)
        else:
            results[v] = {"best_val_loss": "N/A", "total_time_sec": 0, "avg_epoch_time_sec": 0}

    # 4. REPORT GENERATION
    # Helper to format stats for the final summary table
    def get_stat(v, key, fmt_str=".6f"):
        val = results.get(v, {}).get(key, "N/A")
        # If the result is numeric, format it; otherwise return the raw string
        return f"{val:{fmt_str}}" if isinstance(val, (float, int)) else str(val)

    # Build a Markdown/IEEE-style comparison table
    table = (
        "\n\n" + "*"*85 + "\n"
        "🎉 ALL TRAINING RUNS COMPLETED! IEEE PAPER SUMMARY TABLE\n"
        + "*"*85 + "\n\n"
        "| Parameter / Feature       | V1 (Base)  | V2 (Mix)    | V3 (Full)   |\n"
        "|---------------------------|------------|------------|------------|\n"
        "| Residual Blocks            | 10         | 10         | 10         |\n"
        "| 1x1 Projection             | No         | Yes        | Yes        |\n"
        "| Global Skip Connections    | No         | No         | Yes        |\n"
        "| Parameter Conditioning     | Concat     | Concat     | FiLM       |\n"
        "| Est. Parameter Count       | ~ 31k      | ~ 32k      | ~ 40k      |\n"
        "|---------------------------|------------|------------|------------|\n"
        f"| BEST VAL LOSS (Combined)  | {get_stat('v1', 'best_val_loss'):<10} | {get_stat('v2', 'best_val_loss'):<10} | {get_stat('v3', 'best_val_loss'):<10} |\n"
        f"| TOTAL TRAIN TIME (min)    | {get_stat('v1', 'total_time_sec', '.1f'):<10} | {get_stat('v2', 'total_time_sec', '.1f'):<10} | {get_stat('v3', 'total_time_sec', '.1f'):<10} |\n"
        f"| AVG EPOCH TIME (sec)      | {get_stat('v1', 'avg_epoch_time_sec', '.2f'):<10} | {get_stat('v2', 'avg_epoch_time_sec', '.2f'):<10} | {get_stat('v3', 'avg_epoch_time_sec', '.2f'):<10} |\n"
        "|---------------------------|------------|------------|------------|\n"
    )

    # Final Output: Print to console and save to a persistent file
    print(table)
    with open(os.path.join("results", "training_all_results.txt"), "w") as f:
        f.write(table)
        f.write(f"\nSettings: Epochs={args.epochs}, Batch={args.batch_size}, LR={args.lr}, WD={args.weight_decay}\n")

if __name__ == "__main__":
    main()
